// AUTO-GENERATED by scripts/generate-ana-coach-knowledge.ts — DO NOT EDIT.
// Run `npm run generate:coach` to regenerate.
/* eslint-disable */
export interface CoachProductCard { slug: string; name: string; price: string; tagline: string; url: string }
export const COACH_PRODUCTS: Record<string, CoachProductCard> = {
  "build-to-profit": {
    "slug": "build-to-profit",
    "name": "Build to Profit Live Workshop",
    "price": "$497",
    "tagline": "The flagship live workshop offering, teaching foundational monetization strategies.",
    "url": "/landing"
  },
  "10k-launch-lab": {
    "slug": "10k-launch-lab",
    "name": "The $10k Launch Lab",
    "price": "$597",
    "tagline": "A higher-tier workshop focused on consistent 10k launches.",
    "url": "/10k-launch-lab"
  },
  "money-map": {
    "slug": "money-map",
    "name": "The Money Map",
    "price": "$497",
    "tagline": "A complete strategy course covering ICP, offer, positioning, segmentation, messaging, and copy. Note: Currently, the root domain `/` is set ",
    "url": "/"
  },
  "how-to-hit-10k": {
    "slug": "how-to-hit-10k",
    "name": "How to Hit 10k Workshop",
    "price": "$97",
    "tagline": "A lower barrier-to-entry challenge or mini-workshop.",
    "url": "/how-to-hit-10k"
  },
  "100-genius-launch-ideas": {
    "slug": "100-genius-launch-ideas",
    "name": "100 Genius Launch Ideas",
    "price": "$27",
    "tagline": "A digital product detailing successful launch ideas and frameworks.",
    "url": "/100-genius-launch-ideas"
  },
  "first-100-paid-subscribers": {
    "slug": "first-100-paid-subscribers",
    "name": "First 100 Paid Subscribers",
    "price": "$97",
    "tagline": "A comprehensive framework to convert free readers into paying customers and achieve bestseller status.",
    "url": "/first-100-paid-subscribers"
  },
  "unstuck-to-published": {
    "slug": "unstuck-to-published",
    "name": "Unstuck to Published",
    "price": "$97",
    "tagline": "A 60-minute live workshop (with Jessica Best) for Substack creators who are stuck overthinking — walk out with a positioned publication, a s",
    "url": "/unstuck-to-published"
  },
  "build-your-substack": {
    "slug": "build-your-substack",
    "name": "Build Your Substack",
    "price": "$97",
    "tagline": "A workshop helping creators build and launch their Substack publication from scratch. Reuses the same checkout architecture and order bump s",
    "url": "/build-your-substack"
  },
  "creator-bundle": {
    "slug": "creator-bundle",
    "name": "Creator Bundle",
    "price": "$69",
    "tagline": "A bundled product offering with a Launch Stack order bump. Standalone checkout with its own lead table.",
    "url": "/creator-bundle"
  },
  "offer-clarity": {
    "slug": "offer-clarity",
    "name": "The Offer Clarity Sprint",
    "price": "$197",
    "tagline": "A self-paced course that teaches creators how to package expertise into a clear, one-sentence offer that subscribers buy from a single email",
    "url": "/offer-clarity"
  },
  "word-into-money": {
    "slug": "word-into-money",
    "name": "Word Into Money",
    "price": "$97",
    "tagline": "A copywriting workshop teaching creators how to turn their writing into recurring revenue. Embedded Stripe checkout with 3 order bumps (Hook",
    "url": "/word-into-money"
  },
  "your-first-1k-after-corporate": {
    "slug": "your-first-1k-after-corporate",
    "name": "Your First $1K After Corporate",
    "price": "$250",
    "tagline": "A 60-minute live workshop teaching corporate professionals the exact 90-day system to make their first $1,000 online. Uses a direct Stripe P",
    "url": "/your-first-1k-after-corporate"
  },
  "create-viral-digital-product": {
    "slug": "create-viral-digital-product",
    "name": "Create Viral Digital Product",
    "price": "$97",
    "tagline": "A 90-minute LIVE workshop (then recorded — every registrant gets the full replay) that walks creators through finding, validating, and shapi",
    "url": "/create-viral-digital-product"
  },
  "show-dont-tell": {
    "slug": "show-dont-tell",
    "name": "Show Don't Tell - Viral Thumbnail Generator",
    "price": "Starter Package $24.00 / Pro Creator Package $247.00",
    "tagline": "A custom-coded AI agent connecting to Nano Banana (Gemini 2.5 Flash Image) to dynamically generate scroll-stopping brand thumbnails. Protect",
    "url": "/show-dont-tell"
  }
};
